language: node_js
node_js:
- lts/*
- '6'
script:
- npm run report
after_script:
- npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  provider: s3
  access_key_id:
    secure: YJwAlfCRUh8kTAYRfAq6M5h/cwYIH7ucMkgKvix+yL8O6sRKALcq1PhU4G2w3+SP0GLRukcreSYlIZFWrZk4aCFqm1EPLZn2+qKryaYHH8e7vLPkPQcKmw15giIvAdG7QMDTK3KahheamA+AqpSOb7Rkw2t40lDuMAyxa/WPtXixAehUJxlnBgqrWM/c0ebKno3sDUMiKjOxY1UuKjc7eD3NbzIynhPeOttTonu9WyTsUdtPcuxBIm7TuGZOy1hP9ccPTfB4th0TKB2/DbnHcuNtxHizowL2kKO/GZLPNMw0Bv0Z4cWn/zU9x8MpgR68FGjrx2cA2B26W0iRsY4Yg1m1SIit0CyoaUX/seBgRRQ4bOm+PNc0W3CVdJTCofYTdSV2QJIenwp5wyVL1mOfxRRio8ny2tp4EwZdfI5xk27y64qJJiBp0xfVsB4praqluvIT6V5aWMvk5chOBLSlgdqWIhZEI1PelzN52wej526tDM5iQrdGIbY92sR8HaaJ491TOsFPMIL3Uv2j266JDaKTrCr+HvXUisz5AP05hVpsqH9BcaW7gYSgLzkya0FeblRP0k8g2qK11QEchloV5rDQ+VCaY1fHx/JlFTdOQohpCQZ84+gJsFr/NQxxz9Jd2WiOu68ZPZOOTEd4KJTpibWt2dvuyvmLCGO/HoFPoHU=
  secret_access_key:
    secure: ob5DhXzxyRScRoA3mCqIF9kRfc6vISqPgJ1/5A84w7xcF6XsWJC327BVlVZfCGFUAJdkcn8kIO8zB2wKY7HrHwulBe+7U/w+WQWU3jUXrrOblUlNUUEQRd6/G/Kk56lQ2FRc+OzSgUY72Nc49xUxfn7Hes75obKOBSKiSqQ+qsB5j9NOM9ReERO1IeEuAToToEfuuFfHmYvK/JZdIepTC21mYCmSIbO3Nu+fe2qhQgYWy340Q63W0vJL84GMDZQd1NgBEwfAngbMvtW2ZDHipdF6YiXk+FwcRzieaN7Dg0OGDTrU2/wZh/Aazp7JuUY6C1GQnsC7rqKtTq5PpwDuqbWUsaRv533Sq7tp9RYV8pvixHQFDvnb/EfBBxi5nCkJSmhBf0puewWxRq+044B5nAv4YXa+hT/GwZlUnaoncqpDwHemKAZWFAu8kBZXXtcs5ehpaH861e22kc13td1+BHq2mqB8iCPvRBDPYEbFIRhYRxb6yU6kPn55+sdb5NJwdpg/8Gxbo0crk7LXWtqU3z2o9+A1ZUXxlLzbOUGlY5VHKnTfwjOKyEb5geQ/YhsPeCNT8lx3neZgkAjKNExWa0zq0Ooei1HBFoRQO4LmqI+DqFdvcRN2oOW++NrdJhb4g1YP5hQgsphEhj7E0JnsNUGMkYleUmn1tZx0uw2ALC0=
  bucket: okanjo-docs
  skip_cleanup: true
  upload-dir: okanjo-app
  acl: public_read
  detect_encoding: true
  default_text_charset: utf-8
  local_dir: deploy
  on:
    branch: master
    repo: Okanjo/okanjo-app
